changed ternary to &&
libscie/ResearchEquals.com pull request #550
Opened 2022-07-27 04:40 UTC by k3sha7

removed redundant ternary operator

2022-07-27 04:42 UTC, k3sha7 commented
this is my first open source contribution any feedback would be appreciated

2022-07-28 12:52 UTC, chartgerink requested changes
Thanks @k3sha7 for the changes! Most of it looks good, and reduces the amount of code a bit.

I'm not 100% sure what motivated you to make these changes. There is no issue for this and the only one I can think of is #546 - where the example relates to somewhat different places.

Please check out my two review comments and revise your PR in the next two weeks if you'd like for this to be considered further. 

Thanks again for taking the time to contribute! 🙏

2022-07-29 15:52 UTC, nasainsbury commented on app/core/components/NavbarTabs.tsx
> +                    {tab.count && (
I think to fix this you can do `!!tab.count` as opposed to `tab.count`

2022-07-29 15:53 UTC, nasainsbury commented on app/core/components/NavbarTabs.tsx
> +                    {tab.count && (
See here: https://stackoverflow.com/questions/53048037/react-showing-0-instead-of-nothing-with-short-circuit-conditional-component

2022-08-09 10:50 UTC, chartgerink commented
@k3sha7 friendly reminder that we'll close this issue as stale on Friday if there's no further activity 😊 If you're working on this, let us know!

Also [happy to chat on our Discord](https://discord.gg/SefsGJWWSw) if you're having issues and want to chat about it.

2022-08-12 07:53 UTC, chartgerink commented
I am closing this now due to unresponsiveness of the original contributor. We do appreciate the contribution but we can't work through it without your help if there are open questions.

Thanks and hope you're going into a good weekend!

2022-08-12 07:53 UTC, closed without merging

2022-08-12 08:46 UTC, k3sha7 commented
Hi there,
Thanks for getting back to me, I just stumbled across this issue and since
I knew what to do, I gave it a shot.But after further investigation i found
out that using ternary operator is better in most of the cases. So u can
ignore this PR

On Fri, Aug 12, 2022, 1:24 PM Chris Hartgerink ***@***.***>
wrote:

> Closed #550 <https://github.com/libscie/ResearchEquals.com/pull/550>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/libscie/ResearchEquals.com/pull/550#event-7177195219>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVARSJ7OJHB5WMVIHXY2IY3VYX7JRANCNFSM54YE7MQA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-12 10:12 UTC, chartgerink commented
Thanks @k3sha7 - if you'd still like to be credited as a contributor on the repository, feel free to ping me here. We value all contributions, also those that don't end up making it into the code! 🤗