Wrap the edit icon as a button
libscie/ResearchEquals.com pull request #580
Opened 2022-08-05 01:04 UTC by nsunami

This PR wraps the edit icon in a `button` element so that it appears as a button. This will enable focus and hover:cursor-pointer by itself (+ has an added benefit of focusing by tab).

Fixes #579.

2022-08-08 09:04 UTC, chartgerink requested changes
Thanks for the proposed fix @nsunami! 👍 

Could you move the `aria-label` and `onClick` up one level as in the suggested change? I can focus on the button while testing but it doesn't do anything at the moment. The change would need to be linted because I did it only in the browser.

Happy to take it from here if you're too busy as well 😊

2022-08-08 09:04 UTC, chartgerink commented on app/modules/components/ModuleEdit.tsx
> +          </button>
```suggestion
          <button onClick={() => {
                  setIsEditing(!isEditing)
                }} aria-label={isEditing ? "End editing mode without saving" : "Start editing mode"}>
            {isEditing ? (
              <EditOff
                size={24}
                className="h-6 w-6 fill-current text-gray-900 dark:text-gray-200"
              />
            ) : (
              <Edit
                size={24}
                className="h-6 w-6 fill-current text-gray-900 dark:text-gray-200"
              />
            )}
          </button>
```

2022-08-08 23:41 UTC, nsunami commented on app/modules/components/ModuleEdit.tsx
> +          </button>
Applied the changes!

2022-08-08 23:43 UTC, nsunami commented
Thanks, @chartgerink! I applied your changes 👍

2022-08-09 07:07 UTC, chartgerink commented
Hm I don't see changes here @nsunami - did something maybe go wrong in pushing the changes to remote? I still see the `onClick` even on the icon level.

2022-08-09 10:17 UTC, nsunami commented
@chartgerink Sorry I forgot to push my change! It should be here now.

2022-08-09 10:25 UTC, chartgerink approved these changes
Thanks @nsunami 😊 

![](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2022-08-09 11:08 UTC, merged