Upgrade to Blitz 2.0 🔥
libscie/ResearchEquals.com pull request #924
Opened 2022-11-15 15:53 UTC by nsunami

This PR upgrades the app to Blitz 2.0.

(This is still a draft---update the description first soon)

2022-11-21 18:54 UTC, chartgerink requested changes
We're getting there thanks to your fantastic work on this. It's a lot and I appreciate the effort you have and are putting in :pray: See below for blockers, nice to haves, and remaining questions/comments.

Here's a gif to keep us going:

![](https://media.giphy.com/media/qiS3vXMgjPADJKue3a/giphy.gif?cid=ecf05e47q98ogo53ktbb5il1cm4yd3pjn7l82s72j87fpph2&rid=giphy.gif&ct=g)


## Blockers

- [x] verify email not working
```
14:36:43.778 ERROR verify-email() 
 Error  
Invalid `prisma.user.findUnique()` invocation:

{
  where: {
    id: NaN
        ~~~
  },
```
- [x] ORCID authentication didn't work - middleware error - [quick fix tho: wrapping the ORCID api route in `api()` middleware.](https://github.com/blitz-js/blitz/issues/3467#issuecomment-1185676391)
- [ ] Stripe payments not working cuz of Anti-CSRF issue

## Nice to haves

- [ ] Directory tree
	- [ ] Could you provide a short overview of the current directory structure? (also helpful for new contributors!)
	- [ ] Could you remove empty folders?
- [ ] Are there alternatives to the many `.catch(() => {})`? If we could replace those with an `await` or so it would definitely make the code more readably


## Remaining Questions/comments

- [ ] Tested RSS feed?
- [ ] Need to still test Stripe after anti-CSRF is fixed.
- Syntax highlighting looks fine :+1:
- floating promises -> would be good to at least log the error so that we can pinpoint it if something goes wrong. Is there any other way around this as we now repeat something very often that does nothing? (maybe using `await`?)
- You say `Router.push()` is no longer working - any indication why? 
- String manipulation - i reverted the change and did not get an error? It only gets YYYY btw for the references.
- Duplicate `changeTitle` mutations - very good! I think that might have caused some of the issues in the collections too.
- Validating collection description - nice!
- Fonts not loading - removed the loading from the css stylesheet as a result.
- App startup is a bit slow - I notice this too! I figure it'll be better in production as dev tends to be slower. We could think about performance measurements to keep track of this and optimize in the future
- Jest-related issues - we need to add these dependencies to the wiki then!
- build issues - I am confused by the presence of `/__tests__` and `/test` - can we reconcile these?

> I wondered if adding npm run build to pre-push would be better (or is it too much overhead..?). 💭

- I think running build is a lot of overhead indeed. In essence this should not be an issue if everything else works. `npx tsc` should run the tests anyway, and it builds in test deployments too.

2022-11-23 10:33 UTC, nsunami commented on db/seeds.ts
> +export default seed
This may be my VS Code not doing `files.insertFinalNewline` 😓

2022-11-23 11:36 UTC, nsunami commented
Thanks for the review! Below are my progresses:


> ## Blockers


> * [ ]  verify email not working
> 
> ```
> 14:36:43.778 ERROR verify-email() 
>  Error  
> Invalid `prisma.user.findUnique()` invocation:
> 
> {
>   where: {
>     id: NaN
>         ~~~
>   },
> ```

I could not replicate this on my end. I can create an account, and clicking the verification email works fine for me. Could you provide steps to reproduce? 

> * [ ]  ORCID authentication didn't work - middleware error - [quick fix tho: wrapping the ORCID api route in `api()` middleware.](https://github.com/blitz-js/blitz/issues/3467#issuecomment-1185676391)

I pushed https://github.com/libscie/ResearchEquals.com/pull/924/commits/4dc068147a28348abd439929d274c0db22e944c2, and 

> * [ ]  Stripe payments not working cuz of Anti-CSRF issue

The Stripe payments should be working now! 

> ## Nice to haves
> * [ ]  Directory tree
>   
>   * [ ]  Could you provide a short overview of the current directory structure? (also helpful for new contributors!)
>   * [ ]  Could you remove empty folders?

I think Git does not empty folders (and thus I believe empty folders are not pushed to remote--let me know if there are). Would something like doing [git-clean](https://git-scm.com/docs/git-clean/2.22.0) solves this? 

> * [ ]  Are there alternatives to the many `.catch(() => {})`? If we could replace those with an `await` or so it would definitely make the code more readably

Great suggestion! I think just do await makes sense in terms of readability (where catching is not needed) 👍 
 
> ## Remaining Questions/comments
> * [ ]  Tested RSS feed?

Just tested on my localhost and it looks ok 👍 

> * [ ]  Need to still test Stripe after anti-CSRF is fixed.

Now this has been fixed 👍 

> * Syntax highlighting looks fine 👍

> * floating promises -> would be good to at least log the error so that we can pinpoint it if something goes wrong. Is there any other way around this as we now repeat something very often that does nothing? (maybe using `await`?)

Agreed. We can also do `toast.error(e.message)` to provide a more meaningful error message, perhaps together with `console.log(e)`. I tried doing so in our new payment handler: https://github.com/libscie/ResearchEquals.com/pull/924/commits/fcd475582922b7634f41f8c228a2db33f94d1260 

> * You say `Router.push()` is no longer working - any indication why?

`Router` is no longer exported from `blitz`, and thus we cannot use it. Instead, we use NextJS's `useRouter()`. 

> * String manipulation - i reverted the change and did not get an error? It only gets YYYY btw for the references.

Oh, that is weird. Let me check. 

> * Duplicate `changeTitle` mutations - very good! I think that might have caused some of the issues in the collections too.
🙌 

> * Validating collection description - nice!
👍 

> * Fonts not loading - removed the loading from the css stylesheet as a result.

Thanks!

> * App startup is a bit slow - I notice this too! I figure it'll be better in production as dev tends to be slower. We could think about performance measurements to keep track of this and optimize in the future

Yup!

> * Jest-related issues - we need to add these dependencies to the wiki then!

Got it!

> * build issues - I am confused by the presence of `/__tests__` and `/test` - can we reconcile these?

Probably, the best way to move all tests to `/__tests__` following the Jest's convention

> 
> > I wondered if adding npm run build to pre-push would be better (or is it too much overhead..?). 💭
> 
> * I think running build is a lot of overhead indeed. In essence this should not be an issue if everything else works. `npx tsc` should run the tests anyway, and it builds in test deployments too.

Got it!


# Nami's To-Do's 

- [ ] Overview of the directory structure 
- [ ] Converting the floating promises to await
- [ ] Check the string manipulation issues (YYYY?)
- [ ] Add Jest-related dependencies to Wiki
- [ ] Move test files in `/test` to `__tests__`

2022-11-28 16:11 UTC, chartgerink requested changes
This is looking great! 🙏 It is mergeable, save for one thing that needs to be fixed. 1️⃣ 

**almost there!!!!**

## Dashboard does not redirect to log in screen

Right now when I go to the dashboard (when logged out) I get this prisma error:
![Screenshot 2022-11-28 at 17 10 59](https://user-images.githubusercontent.com/2946344/204326277-0e4a4ab8-972d-4bf1-a4bf-96f84a2818d6.png)


In production, I do get the regular login window when I go to the https://researchequals.com/dashboard page while logged out.
![Screenshot 2022-11-28 at 17 11 22](https://user-images.githubusercontent.com/2946344/204326379-e3d4ea9b-6150-41ad-ab5a-61565c4f2175.png)


It's fine for e.g., https://researchequals.com/admin in both production and testing, so I'm not sure where this is coming from 🤔

2022-11-29 10:45 UTC, nsunami commented
Thanks, Chris! 👍 

I tried solving the error on the `/dashboard` when logged out, as follows:

1. https://github.com/libscie/ResearchEquals.com/pull/924/commits/db5a44c831192ae3bbf6a7c762b3ca6dd1c98806 We are now passing `undefined` as `userId` when logged out, and passing this to the DB query. 

2. https://github.com/libscie/ResearchEquals.com/pull/924/commits/962a04c86ed860368504df54b1230db4089736ae After testing this change on GitHub Codespaces, I got another 500 error, `(intermediate value) is not iterable.` in `getDashboardData`. The cause of this issue was that we were trying to ignore the null in this line `...workspace?.following.map((x) => x.id)!` and we did not have a fallback when it was null. To solve this, I added an empty array as a fallback: `...(workspace?.following.map((x) => x.id) ?? [])`

(*Side note: The commit https://github.com/libscie/ResearchEquals.com/pull/924/commits/962a04c86ed860368504df54b1230db4089736ae was not signed because I did not have a GPG key setup on my Codespaces env. 😓 )

Hope this works!

2022-11-29 13:30 UTC, chartgerink approved these changes
![](https://media.giphy.com/media/KSIdkxVvqrbaR67SFN/giphy.gif?cid=ecf05e47t4a5yweiokep5axbc726c7x5anu29k98bts49bal&rid=giphy.gif&ct=g)

2022-11-29 13:44 UTC, merged